### ISSUE TITLE
Export in one unique Geopackage

### ISSUE THREAD

**Issue by katagen** [tarot231/qgis-project-packager-plugin#1]
Hello,
Would it be possible to export all the layers in one unique geopackage?
So at the end, we would have 2 files:
- the project in .qgz
- and the gpkg with all the layers

It would be easiest to explain when we send the package to people... One project and one file with everything in it!
Thank you.

**Comment by tarot231** [comment]
Yeah, I'm thinking about that too. However, I'm not sure when it will be implemented.

**Comment by katagen** [comment]
Any news on that?

**Comment by tarot231** [comment]
Implemented in https://github.com/tarot231/qgis-project-packager-plugin/commit/240835dd1907dd592b60981ecf6e8ff437864487
