### ISSUE TITLE
Vacuum geopackages after moving

### ISSUE THREAD

**Issue by simbamangu** [tarot231/qgis-project-packager-plugin#2]
Feature request: I'd suggest running vacuum on the geopackages moved to the new directory to reduce size - if you're moving a working project to a new place for sharing often the old geopackages are rather large and need cleanup.

(By the way - great plugin, best functionality of any I've tried over the years)

**Comment by tarot231** [comment]
Implemented in https://github.com/tarot231/qgis-project-packager-plugin/commit/240835dd1907dd592b60981ecf6e8ff437864487
