### ISSUE TITLE
Project Packager not working on QGIS 3.38.1-Grenoble

### ISSUE THREAD

**Issue by Alextojo2860** [tarot231/qgis-project-packager-plugin#8]
I get an error:

Project Packager: C:/MyDirectory/MyProjectName.gpkg: No such file or directory

When I try to Store Data in Geopackage.

**Comment by tarot231** [comment]
Thank you for your report. It has reproduced in my environment.

**Comment by tarot231** [comment]
Fixed in v0.7.3
