### ISSUE TITLE
Custom SVG-Symbology causes export to terminate

### ISSUE THREAD

**Issue by hatobi** [tarot231/qgis-project-packager-plugin#9]
When packaging a project that contains custom SVG files as layer styling symbology, the packaging export stops when the layer containing such a symbology is encountered.

<img width="1433" alt="2024-09-06_115645_Screenshot" src="https://github.com/user-attachments/assets/d3e3ccd8-8e55-494b-a1af-951dd6f49c2c">

This happens with all kinds of SVG files and I haven't been able to find a workaround other than removing the symbology completely.

**Comment by tarot231** [comment]
Fixed in v0.7.3
